name: Perforce Klocwork scan

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  klocwork-codescan:
    runs-on: self-hosted
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Print run info
        run: |
          echo "Run ID: $GITHUB_RUN_ID"
          echo "Repository: ${{ github.repository }}"
          echo "Workflow: $GITHUB_WORKFLOW"
          curl checkip.amazonaws.com

      - name: Run Klocwork scan
        uses: cloudbees-io-gha/perforce-klocwork-sast-publish@v1
        with:
          cloudbees-url: ${{ vars.CLOUDBEES_QA_API_URL }}
          url: ${{ vars.KLOCWORK_URL }}
          token: ${{ secrets.NEW_KLOCWORK_APP_TOKEN }}
          license-host: ${{ vars.KLOCWORK_LICENSE }}
          username: ${{ vars.KLOCWORK_USERNAME }}
          project-name: test-cpp1-gha-1
          build-tool: make
          build-options: make -j14
